[package]
name = "spsv2-builder"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
spsv2-errors = { path = "../errors" }
spsv2-types = { path = "../types" }
spsv2-events = { path = "../events" }
spsv2-package = { path = "../package" }
spsv2-manifest = { path = "../manifest" }
spsv2-hash = { path = "../hash" }
spsv2-resolver = { path = "../resolver" }
spsv2-store = { path = "../store" }
spsv2-net = { path = "../net" }
spsv2-install = { path = "../install" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["fs", "process"] }
# rhai = { workspace = true }  # Removed - handled via spsv2-package now
tempfile = { workspace = true }
num_cpus = "1.17.0"
toml = { workspace = true }
minisign = "0.7.9"

[dev-dependencies]
tempfile = { workspace = true }