[workspace]
resolver = "3"
members = [
    "apps/sps2",
    "crates/audit",
    "crates/builder",
    "crates/config",
    "crates/errors",
    "crates/events",
    "crates/hash",
    "crates/index",
    "crates/install",
    "crates/manifest",
    "crates/net",
    "crates/ops",
    "crates/package",
    "crates/resolver",
    "crates/root",
    "crates/state",
    "crates/store",
    "crates/types",
    "tests",
]

[workspace.package]
edition = "2021"
rust-version = "1.86.0"
authors = ["spsv2 Contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/org/spsv2"

[workspace.dependencies]
# Async runtime
tokio = { version = "1.45.1", features = ["full"] }

# Database
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "macros", "migrate"] }

# HTTP
reqwest = { version = "0.12.18", features = ["json", "stream"] }

# Serialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.22"

# Error handling
thiserror = "2.0.12"

# Utilities
uuid = { version = "1.17.0", features = ["v4", "serde"] }
semver = { version = "1.0.26", features = ["serde"] }
blake3 = "1.8.2"
tracing = "0.1.41"
chrono = { version = "0.4.41", features = ["serde"] }

# Concurrent data structures
dashmap = "6.1.0"
crossbeam = "0.8.4"

# Script engine
# rhai = { version = "1.16", features = ["serde"] }  # Removed in favor of Starlark

# CLI
clap = { version = "4.5.39", features = ["derive", "env"] }

# Testing
tempfile = "3.20.0"
proptest = "1.6.0"
futures = "0.3.31"