[format_version]
major = 1
minor = 0
patch = 0

[package]
name = "hello-autotools"
version = "1.0.0"
revision = 1
arch = "arm64"
description = "Test autotools build system"
license = "MIT"

[package.compression]
format = "legacy"

[dependencies]

[sbom]
spdx = "35311cb143842852a40d1a3e4d63fdbc220cb1410d8ce42f6d0402b6c33d8580"
