[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hello-pyproject"
version = "1.0.0"
description = "Test pyproject.toml package"

[project.scripts]
hello-pyproject = "hello:main"