[format_version]
major = 1
minor = 0
patch = 0

[package]
name = "helix"
version = "25.1.1"
revision = 1
arch = "arm64"
description = "vim but in rust"
license = "MIT"

[package.compression]
format = "legacy"

[dependencies]

[sbom]
spdx = "416cf5ac6400cab00be98d6dd6cb9952e1dc68516f3c734888ac9af6d3e9098c"
